### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by laban211** [MaximilianHansson/JULibrary#7]
#Part 3: Creating the business logic layer
- [x] Create Author -Dan
- [ ] Create Book
- [ ] Edit Author
- [ ] Edit Book
- [ ] Create Admin
- [ ] Admin Details
- [ ] Edit Admin(s)
- [ ] Log in
#Part 4: Adding security
- [ ] Validate user actions (Is that user allowed to do that)
- [ ] User permission level
- [ ] Hindra SQL-injections (and store passwords in a safe way)
#Extra
- [ ] Hosting
